// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyArIMFsk3gUP_kmSLBZQJp6aboq6bI4NK4',
    appId: '1:508307779552:web:a3b97731fcd4bcbf7e8585',
    messagingSenderId: '508307779552',
    projectId: 'ai-food-recognizer',
    authDomain: 'ai-food-recognizer.firebaseapp.com',
    storageBucket: 'ai-food-recognizer.firebasestorage.app',
    measurementId: 'G-PDLDHZNVS3',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDEmK477vGvnsmNxPtfOoi6op2lVNytehE',
    appId: '1:508307779552:android:250e4d3199af17327e8585',
    messagingSenderId: '508307779552',
    projectId: 'ai-food-recognizer',
    storageBucket: 'ai-food-recognizer.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyD-r63t5IU7XBnkqab0_2M61yu4VuOx7Ss',
    appId: '1:508307779552:ios:8306142b46a1a30d7e8585',
    messagingSenderId: '508307779552',
    projectId: 'ai-food-recognizer',
    storageBucket: 'ai-food-recognizer.firebasestorage.app',
    iosBundleId: 'com.example.aiFoodRecognizerApp',
  );
}
